# Generated by Django 3.0.7 on 2020-06-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200628_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='name',
            field=models.CharField(default=123, max_length=256),
            preserve_default=False,
        ),
    ]
